#!/bin/sh
set -e

# Xcode Cloud runs this automatically right after cloning the repo, before it resolves the
# project. Two things in this repo are deliberately not committed, and both have to be
# reconstructed here or the build has nothing to work with:
#
#   1. Waypoint.xcodeproj — generated by XcodeGen from project.yml and gitignored, which is the
#      standard setup for xcodegen-managed repos. Without this step Xcode Cloud finds no project
#      at all.
#   2. Secrets.xcconfig — holds the Google Places key and is gitignored so the key never lands in
#      version control. It's rebuilt from an Xcode Cloud environment variable instead.

echo "==> Installing XcodeGen"
brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Recreate the gitignored secrets file from the environment variable configured in the Xcode Cloud
# workflow. Mark GOOGLE_PLACES_API_KEY as *secret* there so it isn't printed in build logs.
#
# If the variable isn't set the build still succeeds: the app degrades to Apple-only place data
# (no photos/ratings/hours) rather than failing, so a misconfigured key shows up as missing
# content in TestFlight rather than a red build.
echo "==> Writing Secrets.xcconfig"
if [ -n "$GOOGLE_PLACES_API_KEY" ]; then
    echo "GOOGLE_PLACES_API_KEY = $GOOGLE_PLACES_API_KEY" > Secrets.xcconfig
else
    echo "warning: GOOGLE_PLACES_API_KEY is not set — place cards will fall back to Apple-only data"
    echo "GOOGLE_PLACES_API_KEY = " > Secrets.xcconfig
fi

echo "==> Generating Waypoint.xcodeproj"
xcodegen generate

echo "==> ci_post_clone complete"
